database:
  bind:
    db_host: 'localhost'
    db_username: 'admin'
    db_password: 'admin'

  pathToEntities: app/Entity
  entityNamespace: App\Entity
  pathToRepositories: app/Repository

  useQueryLog: true

  connections:
    test:
      host: '%db_host%'
      dbname: 'red'
      username: '%db_username%'
      password: '%db_password%'
    test2:
      host: '%db_host%'
      dbname: 'danil'
      username: '%db_username%'
      password: '%db_password%'
